name: mozartNet
channels:
  - defaults
dependencies:
  - python=3.9
  - pip:
    - numpy
    - matplotlib
    - tqdm
    - pygame
  


# ## Environment installation
#1. Make sure you have conda installed in your system.
#2. Then, get the conda_env.yml file, and from the same directory, run conda env create -f conda_env.yml.

# ## Environment update (suppose you want to add a library called my_library)
#1. add my_library to the list of pip dependencies above
#2. deactivate the environment by running "conda deactivate"
#3. update the environment by running "conda env update -f conda_env.yaml"
#4. Wait end of update and run the enironment with "conda activate mozartNet"